config/routes.rb
Rails.application.routes.draw do
  get '/pets', to: "pets#index", as: :pets
  get '/pets/new', to: "pets#new", as: :new_pet
  post '/pets', to: "pets#create"
  get '/pets/:id', to: "pets#show", as: :pet
  get '/pets/:id/edit', to: "pets#edit", as: :edit_pet
  patch '/pets/:id', to: "pets#update"

  delete '/pets/:id', to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['dog', 'cat', 'bat', 'fish']
  validates :name, presence: true
  validates :species, inclusion: {in: SPECIES}

  def found_days_ago
    days = Date.today.day - self.found_on.day
    "was found #{days} days ago"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :found_on, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostKittyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 col-md-6 offset-md-3">
        <%= simple_form_for(pet) do |f|  %>
          <%= f.input :name, class: 'form-control' %>
          <%= f.input :species, collection: Pet::SPECIES, class: 'form-control'%>
          <%= f.input :found_on, class: 'form-control' %>
          <%= f.submit class: 'btn btn-primary w-100'%>
        <% end %>
      </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% @pets.each do |pet| %>
        <h1><%= pet.name %></h1>
        <h3><%= pet.species %></h3>
        <p><em><%= pet.found_days_ago %></em></p>
        <%= link_to "See more about #{pet.name}", pet_path(pet), class: 'btn btn-primary mb-5'%>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p><%= @pet.found_days_ago %></p>
<p><%= @pet.species %></p>

<p><%= link_to "edit this pet", edit_pet_path(@pet) %></p>

<p><%= link_to "delete this pet", pet_path(@pet), method: :delete, data: {confirm: "Are you sure?"} %></p>